 name : build and push to docker hub 

 on : 
   push: 
     branches: 
       - main
 workflow_dispatch:

 env:
   Image-name : {{ secrets.DOCKER_USERNAME }}/my-app:latest 
 jobs:
    build-and-push:
    runs-on: ubuntu-latest
    steps:
     - name : checout in repo
       usesx : actions/checkout@v2
       -name : login into dockerhub
        uses: docker/login-action@v1
        with:
           username:{{ secrets.DOCKER_USERNAME }}
           password:{{ secrets.DOCKER_TOKEN }}

      - name: build image
         run: docker build -t $ {{ env.Image-name }}:latest .
      - name: push image
        run: docker push ${{ env.Image-name }}:latest

    
   